const orders = [
    {
      id: "PO-10045",
      supplier: "ABC Supplies",
      dateCreated: "2024-12-01",
      quantity: "5 Items",
      totalCost: "$12,500",
      status: "Pending",
      actions: "pending",
    },
    {
      id: "PO-10045",
      supplier: "Global Textiles",
      dateCreated: "2024-12-02",
      quantity: "3 Items",
      totalCost: "$7,800",
      status: "Approved",
      actions: "track",
    }, {
        id: "PO-10045",
        supplier: "Global Textiles",
        dateCreated: "2024-12-02",
        quantity: "3 Items",
        totalCost: "$7,800",
        status: "Approved",
        actions: "track",
      }, {
        id: "PO-10045",
        supplier: "Global Textiles",
        dateCreated: "2024-12-02",
        quantity: "3 Items",
        totalCost: "$7,800",
        status: "Approved",
        actions: "track",
      }, {
        id: "PO-10045",
        supplier: "Global Textiles",
        dateCreated: "2024-12-02",
        quantity: "3 Items",
        totalCost: "$7,800",
        status: "Approved",
        actions: "track",
      }, {
        id: "PO-10045",
        supplier: "Global Textiles",
        dateCreated: "2024-12-02",
        quantity: "3 Items",
        totalCost: "$7,800",
        status: "Approved",
        actions: "track",
      }, {
        id: "PO-10045",
        supplier: "Global Textiles",
        dateCreated: "2024-12-02",
        quantity: "3 Items",
        totalCost: "$7,800",
        status: "Approved",
        actions: "track",
      }, {
        id: "PO-10045",
        supplier: "Global Textiles",
        dateCreated: "2024-12-02",
        quantity: "3 Items",
        totalCost: "$7,800",
        status: "Approved",
        actions: "track",
      }, {
        id: "PO-10045",
        supplier: "Global Textiles",
        dateCreated: "2024-12-02",
        quantity: "3 Items",
        totalCost: "$7,800",
        status: "Approved",
        actions: "track",
      }, {
        id: "PO-10045",
        supplier: "Global Textiles",
        dateCreated: "2024-12-02",
        quantity: "3 Items",
        totalCost: "$7,800",
        status: "Approved",
        actions: "track",
      }, {
        id: "PO-10045",
        supplier: "Global Textiles",
        dateCreated: "2024-12-02",
        quantity: "3 Items",
        totalCost: "$7,800",
        status: "Approved",
        actions: "track",
      }, {
        id: "PO-10045",
        supplier: "Global Textiles",
        dateCreated: "2024-12-02",
        quantity: "3 Items",
        totalCost: "$7,800",
        status: "Approved",
        actions: "track",
      }, {
        id: "PO-10045",
        supplier: "Global Textiles",
        dateCreated: "2024-12-02",
        quantity: "3 Items",
        totalCost: "$7,800",
        status: "Completed",
        actions: "track",
      }, {
        id: "PO-10045",
        supplier: "Global Textiles",
        dateCreated: "2024-12-02",
        quantity: "3 Items",
        totalCost: "$7,800",
        status: "Approved",
        actions: "track",
      }, {
        id: "PO-10045",
        supplier: "Global Textiles",
        dateCreated: "2024-12-02",
        quantity: "3 Items",
        totalCost: "$7,800",
        status: "Approved",
        actions: "track",
      }, {
        id: "PO-10045",
        supplier: "Global Textiles",
        dateCreated: "2024-12-02",
        quantity: "3 Items",
        totalCost: "$7,800",
        status: "Approved",
        actions: "track",
      }, {
        id: "PO-10045",
        supplier: "Global Textiles",
        dateCreated: "2024-12-02",
        quantity: "3 Items",
        totalCost: "$7,800",
        status: "Approved",
        actions: "track",
      }, {
        id: "PO-10045",
        supplier: "Global Textiles",
        dateCreated: "2024-12-02",
        quantity: "3 Items",
        totalCost: "$7,800",
        status: "Approved",
        actions: "track",
      }, {
        id: "PO-10045",
        supplier: "Global Textiles",
        dateCreated: "2024-12-02",
        quantity: "3 Items",
        totalCost: "$7,800",
        status: "Approved",
        actions: "track",
      }, {
        id: "PO-10045",
        supplier: "Global Textiles",
        dateCreated: "2024-12-02",
        quantity: "3 Items",
        totalCost: "$7,800",
        status: "Approved",
        actions: "track",
      }, {
        id: "PO-10045",
        supplier: "Global Textiles",
        dateCreated: "2024-12-02",
        quantity: "3 Items",
        totalCost: "$7,800",
        status: "Approved",
        actions: "track",
      }, {
        id: "PO-10045",
        supplier: "Global Textiles",
        dateCreated: "2024-12-02",
        quantity: "3 Items",
        totalCost: "$7,800",
        status: "Approved",
        actions: "track",
      }, {
        id: "PO-10045",
        supplier: "Global Textiles",
        dateCreated: "2024-12-02",
        quantity: "3 Items",
        totalCost: "$7,800",
        status: "Approved",
        actions: "track",
      }, {
        id: "PO-10045",
        supplier: "Global Textiles",
        dateCreated: "2024-12-02",
        quantity: "3 Items",
        totalCost: "$7,800",
        status: "Approved",
        actions: "track",
      }, {
      id: "PO-10045",
      supplier: "Global Textiles",
      dateCreated: "2024-12-02",
      quantity: "3 Items",
      totalCost: "$7,800",
      status: "Approved",
      actions: "track",
    }, {
        id: "PO-10045",
        supplier: "Global Textiles",
        dateCreated: "2024-12-02",
        quantity: "3 Items",
        totalCost: "$7,800",
        status: "Approved",
        actions: "track",
      }, {
        id: "PO-10045",
        supplier: "Global Textiles",
        dateCreated: "2024-12-02",
        quantity: "3 Items",
        totalCost: "$7,800",
        status: "Approved",
        actions: "track",
      }, {
        id: "PO-10045",
        supplier: "Global Textiles",
        dateCreated: "2024-12-02",
        quantity: "3 Items",
        totalCost: "$7,800",
        status: "Approved",
        actions: "track",
      },
  ];
  export {orders}